version: '1'

services:
  pollash:
    container_name: pollash
    image: reysie7e/pollash
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - microservicesnetwork
networks:
  microservicesnetwork:
    driver: bridge
volumes:
  db-data: {}
